storage:
  #Type storage:
  # Local - file in plugin folder
  # MongoDB - MongoDB NoSQL storage
  # MySQL - MySQL storage
  type: MongoDB

  setting:
    #host where store storage, if your use Local this parameter ignore
    host: localhost

    #name user at DB
    user: user

    #password at DB
    password: password

    #name at DB
    databaseName: TradingPlatform

    #port at DB
    port: 27017
settings:
  #Supported language:
  #   russia
  #   english
  lang: english
  betSpread:
  - 1
  - 10
  - 100
  - 1000
  - 10000

#Setup Socket settings
socket:
  enable: false
  port: 2424
  charset: UTF-8